version: '3'

services:
    ...
    adminer:
        restart: always
        image: adminer
        volumes:
            - ./docker/adminer/pinkpastel:/var/www/html/designs/pinkpastel
        expose:
            - "8080"
        ports:
            - "8088:8080"
        environment:
            ADMINER_DEFAULT_SERVER: mysql
            ADMINER_DESIGN: "pinkpastel"
